export const MODAL_IDS = {
  GOOGLE_SELECT_CONNECTION_MODAL: 'GOOGLE_SELECT_CONNECTION_MODAL',
  SELECT_PROVIDER_MODAL: 'SELECT_PROVIDER_MODAL',
  ENABLE_GOOGLE_IMAP_MODAL: 'ENABLE_GOOGLE_IMAP_MODAL',
  GOOGLE_OAUTH_CONNECTION_MODAL: 'GOOGLE_OAUTH_CONNECTION_MODAL',
  GOOGLE_PASSWORD_CONNECTION_MODAL: 'GOOGLE_PASSWORD_CONNECTION_MODAL',
  GOOGLE_APP_PASSWORD_INFO_MODAL: 'GOOGLE_APP_PASSWORD_INFO_MODAL',
  GOOGLE_APP_PASSWORD_FORM_MODAL: 'GOOGLE_APP_PASSWORD_FORM_MODAL',
};
