export const NOTIFICATION = {
  CONNECT_ACCOUNT: 'CONNECT_ACCOUNT',
  RECONNECT_ACCOUNT: 'RECONNECT_ACCOUNT',
  DELETE_ACCOUNT: 'DELETE_ACCOUNT',
  CAMPAIGN_START: 'CAMPAIGN_START',
  CAMPAIGN_STOP: 'CAMPAIGN_STOP',
};
